# Copyright (c) 2026 The Frontier Framework Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR MIT

name: Generate Cargo License Files

on:
  workflow_call:
  push:
    branches: [ main ]
    paths: [ '.frontier/Cargo.lock' ]

permissions:
  contents: write

jobs:
  generate-cargo-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo Binary
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-about
          key: ${{ runner.os }}-cargo-about

      - name: Install Tools
        if: steps.cache-bin.outputs.cache-hit != 'true'
        run: |
          cargo install cargo-about
          cargo install cargo-deny

      - name: Generate NOTICE-CARGO
        run: cargo about generate about-cargo.hbs --manifest-path .frontier/Cargo.toml > NOTICE-CARGO

      - name: Generate SPDX JSON
        run: cargo deny --root .frontier list -f json > LICENSE-CARGO.spdx.json

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update LICENSE-CARGO.spdx.json and NOTICE-CARGO"
          file_pattern: 'LICENSE-CARGO.spdx.json NOTICE-CARGO'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}