# Copyright (c) 2026 The Frontier Framework Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR MIT

name: Generate Cargo License Files

on:
  workflow_call:
  push:
    branches: [ main ]
    paths: [ '.frontier/Cargo.lock' ]

permissions:
  contents: write

jobs:
  generate-cargo-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall

      - name: Install tools
        run:  cargo binstall --no-confirm cargo-about cargo-sbom

      - name: Generate NOTICE-CARGO
        run: |
          cd .github/workflows/cargo-license/
          cargo about generate ../../../about-cargo.hbs --manifest-path ../../../.frontier/Cargo.toml > LICENSE/NOTICE-CARGO

      - name: Generate SPDX JSON
        run: |
          cd .frontier/
          cargo sbom > ../LICENSE/LICENSE-CARGO.spdx.json

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update and LICENSE-CARGO.spdx.json NOTICE-CARGO"
          file_pattern: 'LICENSE-CARGO.spdx.json NOTICE-CARGO'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}