# Copyright (c) 2026 The Frontier Framework Authors
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: Generate Cargo Notices

on:
  workflow_call:
  push:
    branches: [ main ]
    paths: [ '.frontier/Cargo.lock' ]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo Binary
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-about
          key: ${{ runner.os }}-cargo-about

      - name: Install cargo-about
        run: |
          if ! command -v cargo-about &> /dev/null; then
            echo "cargo-about nÃ£o encontrado no cache. Instalando..."
            cargo install cargo-about
          else
            echo "cargo-about restaurado do cache com sucesso!"
          fi

      - name: Generate NOTICES-CARGO
        run: cargo about generate .frontier/about.hbs --manifest-path .frontier/Cargo.toml > NOTICES-CARGO

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update third-party cargo notices [skip ci]"
          file_pattern: 'NOTICES-CARGO'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}