name: Build Frontier Release

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Organize and Clean
        run: |
          rm -rf .gitignore .github README.md MANUAL.md ROADMAP.md LOGS.md
          mv LICENSE NOTICE .frontier/

      - name: Create ZIP
        run: zip -r Frontier.zip .

      - name: Create Release and Upload File
        uses: softprops/action-gh-release@v2
        with:
          name: "Frontier - ${{ github.ref_name }}"
          body: |
            ## Changed in this version:
            *(Generated automatically by GitHub Actions)*

          generate_release_notes: true
          files: Frontier.zip
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_WORKFLOW_TOKEN }}