# Copyright (c) 2026 The Frontier Framework Authors
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: Build Frontier Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  spdx:
    uses: ./.github/workflows/spdx.yml

  package:
    needs: [ spdx ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Organize and Clean
        run: |
          mv -f LICENSE-APACHE LICENSE-MIT LICENSE.spdx.json NOTICE NOTICES-CARGO .frontier/
          mkdir ../temp
          mv .frontier/ back.bat build.bat front.bat ../temp/
          rm -rf ..?* .[!.]* *
          mv ../temp/* .

      - name: Create ZIP
        run: zip -r Frontier.zip .

      - name: Scan with VirusTotal
        id: vt_scan
        run: |
          FILE_HASH=$(sha256sum Frontier.zip | cut -d ' ' -f 1)
          curl --request POST \
            --url https://www.virustotal.com/api/v3/files \
            --header "x-apikey: ${{ secrets.VIRUSTOTAL_API_KEY }}" \
            --form "file=@Frontier.zip"
          
          echo "REPORT_URL=https://www.virustotal.com/gui/file/$FILE_HASH" >> $GITHUB_ENV

      - name: Create Release and Upload File
        uses: softprops/action-gh-release@v2
        with:
          name: "Frontier - ${{ github.ref_name }}"
          body: |
            [![Downloads](https://img.shields.io/github/downloads/${{ github.repository }}/${{ github.ref_name }}/total)](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}) [![VirusTotal](https://img.shields.io/badge/virustotal-status-navy)](${{ env.REPORT_URL }})
            
          generate_release_notes: true
          files: Frontier.zip
          prerelease: ${{ contains(github.ref_name, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}