name: Build Frontier Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Organize and Clean
        run: |
          rm -rf .github .git .gitignore README.md MANUAL.md ROADMAP.md LOGS.md
          mv LICENSE NOTICE .frontier/

      - name: Create ZIP
        run: zip -r Frontier.zip .

      - name: Create Release and Upload File
        uses: softprops/action-gh-release@v2
        with:
          name: "Frontier - ${{ github.ref_name }}"
          generate_release_notes: true
          files: Frontier.zip
          prerelease: ${{ contains(github.ref_name, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}