# Copyright (c) 2026 The Frontier Framework Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR MIT

name: Generate SPDX License Document

on:
  workflow_call:
  push:
    tags:
      - '*'
      - '!v*'

permissions:
  contents: write

jobs:
  update-cargo-dependencies:
    uses: ./.github/workflows/cargo-update.yml

  generate-spdx:
    needs: [ update-cargo-dependencies ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Generate SBOM (SPDX)
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: LICENSE/LICENSE.spdx.json
          artifact-name: "Frontier Framework"
          upload-release-assets: false

      - name: Link and Format SPDX
        run: |
          CARGO_MD5=$(md5sum LICENSE/LICENSE-CARGO.spdx.json | cut -d' ' -f1)
          jq --arg md5 "$CARGO_MD5" \
            '.externalDocumentRefs += [{
              "externalDocumentId": "DocumentRef-Cargo-Deps",
              "spdxDocument": "LICENSE/LICENSE-CARGO.spdx.json",
              "checksum": { "algorithm": "MD5", "checksumValue": $md5 }
            }]' LICENSE/LICENSE.spdx.json > formatted.json
          mv formatted.json LICENSE/LICENSE.spdx.json

      - name: Commit SPDX Document
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update LICENSE.spdx.json"
          file_pattern: 'LICENSE.spdx.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}