# Copyright (c) 2026 The Frontier Framework Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR MIT

name: Generate SPDX License Document

on:
  workflow_call:
  push:
    tags:
      - '*'
      - '!v*'

permissions:
  contents: write

jobs:
  update-cargo-dependencies:
    uses: ./.github/workflows/cargo-update.yml

  generate-spdx:
    needs: [ update-cargo-dependencies ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

- name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Fetch Dependencies
        run: cargo fetch --manifest-path .frontier/Cargo.toml

      - name: Generate SBOM (SPDX)
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: LICENSE.spdx.json
          artifact-name: "Frontier Framework"
          artifact-version: ${{ github.ref_name }}

      - name: Commit SPDX Document
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update LICENSE.spdx.json"
          file_pattern: 'LICENSE.spdx.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}