# Copyright (c) 2026 The Frontier Framework Authors
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: Generate SPDX License Document

on:
  workflow_call:
  push:
    tags:
      - '*'
      - '!v*'

permissions:
  contents: write

jobs:
  update-cargo:
    uses: ./.github/workflows/update-cargo.yml

  generate:
    needs: [ update-cargo ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Generate SBOM (SPDX)
        uses: anchore/sbom-action@v0
        with:
          path: .frontier/
          format: spdx-json
          output-file: LICENSE.spdx.json
          artifact-name: "Frontier Framework"
          artifact-version: ${{ github.ref_name }}

      - name: Commit SPDX Document
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update LICENSE.spdx.json for version ${{ github.ref_name }} [skip ci]"
          file_pattern: 'LICENSE.spdx.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}